<?php
$links = [
  [
    'route' => '',
    'label' => 'Coinshare',
  ],
  [
    'route' => 'user/jobs',
    'label' => 'My jobs',
  ],
  [
    'route' => 'user/account',
    'label' => 'My account',
  ],
  [
    'route' => 'user/login',
    'label' => 'Login',
  ],
  [
    'route' => 'help/faq',
    'label' => 'Help',
  ],
];
?>

<?php foreach ($links as $i => $link) { 
  if ($vars['route'] == 'index/index') {
    $vars['route'] = '';
  }
?>

  <?php if ($vars['route'] == $link['route']) { ?>
    <b><?=$link['label']?></b> 
  <?php } else { ?>
    <a href='<?="{$vars['baseUrl']}/{$link['route']}"?>'><?=$link['label']?></a>
  <?php } ?>

  <?php if ($i+1 != count($links)) { ?>

    |

  <?php } ?>

<?php } ?>

<br>

<p>


