<html>
<head>
    <title>CoinShare.org - Bitcoin Jobs &amp; Stocks</title>
</head>
<body>

<?php
$links = [
  [
    'route' => '',
    'label' => 'CoinShare - Job Listings',
  ],
  [
    'route' => 'user/jobs',
    'label' => 'My jobs',
  ],
  [
    'route' => 'biz/start',
    'label' => 'Start a business',
  ],
  [
    'route' => 'user/account',
    'label' => 'My account',
  ],
  [
    'route' => 'user/login',
    'label' => 'Login',
  ],
  [
    'route' => 'user/signup',
    'label' => 'Signup',
  ],
  [
    'route' => 'help/faq',
    'label' => 'Help',
  ],
];
?>

<?php foreach ($links as $i => $link) { 
  if ($vars['route'] == 'index/index') {
    $vars['route'] = '';
  }
?>

  <?php if ($vars['route'] == $link['route']) { ?>
    <b><?=$link['label']?></b> 
  <?php } else { ?>
    <a href='<?="{$vars['baseUrl']}/{$link['route']}"?>'><?=$link['label']?></a>
  <?php } ?>

  <?php if ($i+1 != count($links)) { ?>

    |

  <?php } ?>

<?php } ?>

<br>

<p>


