<html>
<head>
    <title>CoinShare.org - Bitcoin Jobs &amp; Stocks</title>
</head>
<body>

<?php $links = $vars['menu']->getLinks(); ?>

<?php foreach ($links as $i => $link) { 
  if ($vars['route'] == 'index/index') {
    $vars['route'] = '';
  }
?>

  <?php if ($vars['route'] == $link['route']) { ?>
    <b><?=$link['label']?></b> 
  <?php } else { ?>
    <a href='<?="{$vars['baseUrl']}/{$link['route']}"?>'><?=$link['label']?></a>
  <?php } ?>

  <?php if ($i+1 != count($links)) { ?>

    |

  <?php } ?>

<?php } ?>

<br>

<p>


