<?php include('header.phtml'); ?>
Welcome to CoinShare - Easy Bitcoin Freelancing and Investing!<br>
<ul>
    <li>Find jobs and earn Bitcoin or stock in a business</li>
    <li>Invest in Bitcoin businesses</li>
    <li>Reap rewards of investment and shares directly in Bitcoin</li>
    <li>Instantly start your own Bitcoin business</li>
    <li>No paperwork!</li>
</ul>

To get started, <a href='<?=$vars['baseUrl']?>/user/signup'>signup for a new account</a> - it's totally free.
<?php include('footer.phtml'); ?>
