<?php include('header.phtml'); ?>

<h3 class="muted">Home</h3>

<?php if (isset($vars['message'])) { ?>
<p><i><span style='color:orangered'><?=$vars['message']?></span></i></p>
<?php } ?>

<?php if (isset($vars['mailMessage'])) { ?>
<p><i><span style='color:orangered'><?=$vars['mailMessage']?></span></i></p>
<?php } ?>

<?php if (!$vars['loggedIn']) { ?>

<h4>What is Bitvest.org?</h4>
<p>
    Bitvest.org is a freelancing site that offers both traditional direct payout and
    share-based payout. Shares can offer dividends, or can be sold in the
    marketplace just like a stock market exchange. The best part, though, is that
    it's completely free and private. Earnings and dividends are paid in Bitcoin,
    and you never have to supply your name or other identification. It's an open,
    private, international free-market digital economy.
</p>
<h4>Why share-based payout?</h4>
<p>
    While direct payout is simpler, becoming a part-owner can be a huge incentive 
    to do higher quality work. This incentive also helps teams that lack capital. 
    By owning shares, workers can build a long-term investment portfolio for
    passive income opportunity or selling shares at greater profit later.
</p>
<h4>How do I join?</h4>

Just signup for a free account here: <a href='<?=$vars['baseUrl']?>/user/signup'><button class='btn btn-primary'>Signup for a free account</button></a>

<?php } ?>

<?php include('footer.phtml'); ?>
