<?php include('header.phtml'); ?>

<!--
<form method='post' action='<?=$vars['baseUrl']?>/user/login-submit'>
<table>
<tr>
    <td>Email:</td><td> <input type='text' name='email' value="<?=$vars['formValues']['email']?>"></td><td style='color:red'><?=$vars['formErrors']['email']?></td>
</tr>
<tr>
<td>Password: </td><td><input type='password' name='password'></td>
<td><a href='<?=$vars['baseUrl']?>/user/forgot-password'>I forgot my password</a> </td>
</tr>
<tr>
<td></td><td> <input type='submit' value='Login'></td>
</tr>
</table>
</form>-->

<form class="form-horizontal" method="post" action="<?=$vars['baseUrl']?>/user/login-submit">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" name="email" placeholder="Email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password</label>
    <div class="controls">
      <input type="password" id="inputPassword" name="password" placeholder="Password">
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox"> Remember me
      </label>
      <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
  </div>
</form>




<?php include('footer.phtml'); ?>
