<?php include('header.phtml'); ?>

<form method='post' action='<?=$vars['baseUrl']?>/user/signup-submit' autocomplete='off'>
<table>
<tr>
<td>Email:</td><td> <input type='text' name='email' value=''></td>
</tr>
<tr>
<td>Password: </td><td><input type='password' name='password'></td>
</tr>
<tr>
<td></td><td> <input type='submit' value='Create a new account'></td>
</tr>
</table>
</form>


<?php include('footer.phtml'); ?>
