<?php include(__DIR__ . '/../header.phtml'); ?>
<h2>Signup for a free account</h2>
<form method='post' action='<?=$vars['baseUrl']?>/user/signup-submit' autocomplete='off'>
<table>
<tr>
    <td>Email:</td><td> <input type='text' name='email' value='<?=$vars['formValues']['email']?>'></td><td style='color:red'><?=$vars['formErrors']['email']?></td>
</tr>
<tr>
    <td>Password: </td><td><input type='password' name='password'></td><td style='color:red'><?=$vars['formErrors']['password']?></td>
</tr>
<tr>
<td></td><td> <input type='submit' value='Create account'></td>
</tr>
</table>
</form>


<?php include(__DIR__ . '/../footer.phtml'); ?>
